name: now_services
description: Project containing now services.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  dio: ^4.0.6
  http: ^0.13.5
  connectivity_plus: ^3.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
